### ISSUE TITLE
Makefile:978: recipe for target 'flowtable/flowtable.api.json' failed

### ISSUE THREAD

**Issue by zhaopcm** [GabrielGanne/vpp-flowtable-plugin#1]
make error because vppapigen dose't have argument --josn, please tell me how can I fix this error.
![2019-12-02 162410](https://user-images.githubusercontent.com/26382837/69943503-5fe1ed00-1520-11ea-9703-cb084b9fd9fb.png)

**Comment by GabrielGanne** [comment]
Hi @zhaopcm 

The vpp api has changed a lot in 3 years, and I am not maintaining this code anymore.

I have updated (quick & dirty) the code for it to work with upstream vpp. It should at least build now (6fa6cf88d95378cb7ca6788baab54451e5278f42).

If this idea interests you, feel free to take over.

Best regards
